version: "3"

services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root # para facilitar instalar docker cli e permissões
    ports:
      - "8085:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y docker.io &&
        service docker start || true &&
        /usr/bin/tini -- /usr/local/bin/jenkins.sh
      "

volumes:
  jenkins_home:
